version: '2'
services:
  pttg-family-migration-ui:
    container_name: FC-container
#    build: .
    image: quay.io/ukhomeofficedigital/pttg-family-migration-ui:0.1.0
    ports:
     - "8000:8000"
    #use external links for containers started outside this compose
    links:
     - pttg-income-proving-api
  pttg-income-proving-api:
    container_name: income-container
    image: quay.io/ukhomeofficedigital/pttg-family-migration-api:0.1.0
    ports:
     - "8081:8081"
  pttg-test-mongodb:
    container_name: mongo-container
    image: quay.io/ukhomeofficedigital/pttg-test-mongodb:0.1.0
    ports:
     - "8888:27017"
  pttg-test-loader-mongodb:
    container_name: mongo-loader-container
    image: quay.io/ukhomeofficedigital/pttg-test-loader-mongodb:0.1.0





# Prerequisites

# - Linked services - host in linked service URL must match service name defined above eg. http://income:8081
# - Any ports required for docker container coummunication must be exposed in the source application's dockerFile eg:
#      .. ..
#      EXPOSE 8081
#      .. ..
# -. Any port to be published to the host machine eg accessible from localhost should have a port definition
